version: '3.8'

services:
  rpc-client:
    build: .
    environment:
      - RPC_URL=https://rpc.anoncenomics.com
      - RPC_USER=${RPC_USER}
      - RPC_PASS=${RPC_PASS}
      - RPC_TIMEOUT=60
    volumes:
      - ./:/app
    working_dir: /app
    command: ["node", "node_polkadot_example.mjs"]
    restart: unless-stopped

  # Alternative: Python client
  rpc-client-python:
    image: python:3.11-slim
    environment:
      - RPC_URL=https://rpc.anoncenomics.com
      - RPC_USER=${RPC_USER}
      - RPC_PASS=${RPC_PASS}
    volumes:
      - ./:/app
    working_dir: /app
    command: >
      sh -c "pip install requests &&
             python python_example.py"
    restart: unless-stopped
